<?php 
require_once('wp-bootstrap-navwalker.php');
require_once('supports.php');
//require_once('customizer.php');
require_once('menus.php');
require_once('hooks.php');
//require_once('tiny-mce.php');
require_once('post-types.php');
require_once('get-data.php');
require_once('display-data.php');
require_once('helpers.php');
require_once('theme-options.php');
require_once('shortcodes.php');
require_once('modules.php');